environment:
  nodejs_version: "6"
  skip_tags: false

install:
  - npm install
  - ./node_modules/.bin/webpack -p
  - npm run build

build: off

build_script:
  - ./node_modules/.bin/build --config ./electron-builder.yml --win -p always
  
test: off
