environment:
  nodejs_version: "8"
  skip_tags: false

install:
  - ps: Install-Product node 8 x86
  - node -v
  - npm install
  - ./node_modules/.bin/webpack -p
  - npm run build

build: off

build_script:
  - ./node_modules/.bin/build --config ./electron-builder.yml --win -p always
  
test: off
